Added translations and implementation of javascript I18N according to Wordpress

diff --git a/deploy_to_wordpress b/deploy_to_wordpress
--- a/deploy_to_wordpress
+++ b/deploy_to_wordpress
@@ -2,30 +2,17 @@
 
 source  .env
 
-MESSAGE=""
 RELEASE="1"
 MAJOR="0"
 MINOR="0"
-DRY="0"
-NOGIT="0"
-MAKEZIP="0"
-SVN="0"
+MICRO="0"
+DOPOT="0"
 
 while [ $# -gt 0 ]
 do
     arg=$1
     shift
     
-    if [[ "x$arg" = "x-s" ]]
-    then
-        RELEASE="0"
-    fi
-
-    if [[ "x$arg" = "x-q" ]]
-    then
-        SVN="1"
-    fi
-
     if [[ "x$arg" = "x-v" ]]
     then
         RELEASE="1"
@@ -38,43 +25,23 @@ do
         MAJOR="1"
     fi
 
-    if [[ "x$arg" = "x-m" ]]
-    then    
-        MESSAGE="$1"
-        shift
+    if [[ "x$arg" = "x-p" ]]
+    then
+        DOPOT="1"
     fi
 
-    if [[ "x$arg" = "x-n" ]]
-    then    
-        DRY="1"
-    fi
-
-    if [[ "x$arg" = "x-z" ]]
-    then    
-        MAKEZIP="1"
-    fi
-
-#    if [[ "x$arg" = "x-g" ]]
-#    then    
-#        NOGIT="1"
-#    fi
 
     if [[ "x$arg" = "x-h" ]]
     then
         echo "Deploy to Wordpress script"
-        echo "Copyright (C) 2020 muis IT https://www.muisit.nl"
+        echo "Copyright (C) 2020-2023 muis IT https://www.muisit.nl"
         echo ""
         echo "deploy_to_wordpress [options]"
         echo ""
-#        echo "-g           no git version bump, version was set already"
         echo "-h           print this help text"
-        echo "-m <msg>     specify commit message"
-        echo "-n           perform a dry-run, printing the raw commands"
-        echo "-q           SVN commits"
+        echo "-p           search strings and regenerate the POT file"
         echo "-r           release a major release (tag with major value upgraded)"
-        echo "-s           surpress releasing (only copy files, no commits)"
         echo "-v           release a minor release (tag with minor value upgraded)"
-        echo "-z           create a zipfile that can be uploaded"
         echo ""
         echo "Add the WPDIR directory location of the destination SVN repository in the"
         echo ".env file next to this script. Set the PROJECT variable to the name of"
@@ -83,42 +50,38 @@ do
     fi
 done
 
-if [[ "x$DRY" = "x1" ]]
+if [[ "x$DOPOT" = "x1" ]]
 then
-    echo "Dry-run, no execution"
-else
-    # perform a production build before we deploy
-    npm run build
+    echo "Creating POT file"
+    $WPCLI i18n make-pot . languages/memberdata-ranking.pot --exclude="vue" --include="lib,models,controllers,assets,dist,memberdata-ranking.php"
+    echo "Update PO files"
+    $WPCLI i18n update-po languages/memberdata-ranking.pot
 fi
 
-#if [[ "x$NOGIT" = "x1" && "x$MAJOR" = "x1" ]]
-#then
-#    echo "-g requires version in .Git to be leading, ignoring -r"
-#    MAJOR=0
-#fi
-#if [[ "x$NOGIT" = "x1" && "x$MINOR" = "x1" ]]
-#then
-#    echo "-g requires version in .Git to be leading, ignoring -v"
-#    MINOR=0
-#fi
-#if [[ "x$MAJOR" = "x1" && "x$MINOR" = "x1" ]]
-#then
-#    echo "Major release requires a minor version of 0, ignoring -v"
-#    MINOR="0"
-#fi
+# always just update the language files
+echo "Updating I18N output files"
+rm -f languages/*.mo languages/*.json
+$WPCLI i18n make-mo languages
+$WPCLI i18n make-json languages --pretty-print --no-purge
 
-#if [[ "x$MESSAGE" = "x" && "x$RELEASE" = "x1" ]]
-#then
-#    echo "Message required for release"
-#    exit
-#fi
+# not releasing, just quit
+if [[ "x$DOPOT" = "x1" ]]
+then
+    exit 0
+fi
+
+if [[ "x$MAJOR" = "x1" && "x$MINOR" = "x1" ]]
+then
+    echo "Major release requires a minor version of 0, ignoring -v"
+    MINOR="0"
+fi
 
 VERSION=`grep "* Version" "$PROJECT.php" | sed 's/[^0-9]*\([0-9\.]*\).*/\1/'`
 MAJ=`echo $VERSION | sed 's/\([0-9]*\).*/\1/'`
 MIN=`echo $VERSION | sed 's/[0-9]*\.\([0-9]*\).*/\1/'`
 MICR=`echo $VERSION | sed 's/[0-9]*\.[0-9]*\.\([0-9]*\)/\1/'`
 
-if [[ "x1" == "x$MAJOR" ]]
+if [[ "x1" = "x$MAJOR" ]]
 then
     echo "Performing major release"
     let "MAJ=$MAJ+1"
@@ -131,112 +94,69 @@ else
         let "MIN=$MIN+1"
         MICR="0"
     else
-        if [[ "x$NOGIT" = "x0" && "x$RELEASE" = "x1" ]]
+        if [[ "x$RELEASE" = "x1" ]]
         then
             echo "Performing micro release"
             let "MICR=$MICR+1"
-        else
-            echo "Version defined by .Git"
         fi
     fi
 fi
 
 echo "Version ${MAJ}.${MIN}.${MICR}"
 
-if [[ "x$NOGIT" = "x0" ]]
+#echo "Running JS tests"
+#npm run --silent test -- --silent >/dev/null 2>&1
+#if [[ ! "x$?" = "x0" ]]
+#then
+#    echo "Javascript tests fail, please run tests yourself"
+#    echo "npm run --silent test"
+#    exit 1
+#else 
+#    echo "Javascript tests succeed"
+#fi
+
+#phpunit --bootstrap tests/preload.php --testdox --colors=always tests 
+#phpunit --bootstrap tests/preload.php --stderr tests 2>/dev/null
+#if [[ ! "x$?" = "x0" ]]
+#then
+#    echo "PHPUnit tests fail, please run tests yourself"
+#    echo "phpunit --bootstrap tests/preload.php --testdox --colors=always tests"
+#    exit 1
+#else
+#    echo "PHPUnit tests succeed"
+#fi
+
+cat "$PROJECT.php" | sed "s/\(.*Version[ \t:]*\).*/\1${MAJ}.${MIN}.${MICR}/" > tmp.$$
+mv tmp.$$ "$PROJECT.php"
+cat "$PROJECT.php" |  sed "s/\(define.*VERSION[^\"]*\"\)[^\"]*\(\".*\)/\1${MAJ}.${MIN}.${MICR}\2/"  > tmp.$$
+mv tmp.$$ "$PROJECT.php"
+
+pushd vue > /dev/null
+cat "package.json" | sed "s/\(.*\"version\"[ \t:]*\"\).*/\1${MAJ}.${MIN}.${MICR}\",/" > tmp.$$
+mv tmp.$$ "package.json"
+popd > /dev/null
+
+# perform a production build before we deploy
+pushd vue > /dev/null
+npm run build
+STAT=$?
+popd > /dev/null
+
+if [ ! "x$STAT" = "x0" ]
 then
-    if [[ "x$DRY" = "x1" ]]
-    then
-        echo "cat \"$PROJECT.php\" | sed \"s/\(.*Version[ \t:]*\).*/\1${MAJ}.${MIN}.${MICR}/\" > tmp.$$"
-        echo "mv tmp.$$ \"$PROJECT.php\""
-        echo "cat \"package.json\" | sed \"s/\(.*version\\\"[ \t:]*\\\"\).*/\1${MAJ}.${MIN}.${MICR}\\\",/\" > tmp.$$"
-        echo "mv tmp.$$ \"package.json\""
-#        echo "git commit -m \"Version bump to ${MAJ}.${MIN}.${MICR}\""
-#        echo "git tag -a \"v${MAJ}.${MIN}.${MICR}\" -m \"Tagged version ${MAJ}.${MIN}.${MICR}\""
-#        echo "git push"
-    else
-        cat "$PROJECT.php" | sed "s/\(.*Version[ \t:]*\).*/\1${MAJ}.${MIN}.${MICR}/" > tmp.$$
-        mv tmp.$$ "$PROJECT.php"
-        cat "package.json" | sed "s/\(.*version\"[ \t:]*\"\).*/\1${MAJ}.${MIN}.${MICR}\",/" > tmp.$$
-        mv tmp.$$ "package.json"
-#        git commit -m "Version bump to ${MAJ}.${MIN}.${MICR}"
-#        git tag -a "v${MAJ}.${MIN}.${MICR}" -m "Tagged version ${MAJ}.${MIN}.${MICR}"
-#        git push
-    fi
+    exit 1
 fi
 
 mkdir -p $WPDIR/trunk
-for i in *.php ./dist LICENSE ./models README.md readme.txt
-do
-    if [[ "x$DRY" = "x1" ]]
-    then
-        echo "cp -r -v $i $WPDIR/trunk"
-    else
-        cp -r -v $i $WPDIR/trunk
-    fi
-done
+cp -r -v *.php LICENSE readme.txt controllers lib models vendor dist $WPDIR/trunk
+mkdir -p $WPDIR/trunk/languages
+cp -v languages/*.mo $WPDIR/trunk/languages
 
-mkdir -p $WPDIR/assets
-for i in `find ./ -type f -path ./assets/\*`
-do
-    if [[ "x$DRY" = "x1" ]]
-    then
-        echo "cp -v $i $WPDIR/assets"
-    else
-        cp -v $i $WPDIR/assets
-    fi
-done
+pushd /tmp > /dev/null
+cp -darpv $WPDIR/trunk /tmp/$PROJECT
+zip -r $PROJECT $PROJECT
+mv $PROJECT.zip $WPDIR
+rm -rf /tmp/$PROJECT
+popd > /dev/null
 
-if [[ "x$MAKEZIP" = "x1" ]]
-then
-    cd /tmp
-    cp -darpv $WPDIR/trunk /tmp/$PROJECT
-    zip -r $PROJECT $PROJECT
-    mv $PROJECT.zip $WPDIR/..
-    rm -rf /tmp/$PROJECT
-fi
-
-if [[ "x1" = "x$RELEASE" ]]
-then
-    if [[ "x1" = "x$SVN" ]]
-    then
-        echo "Releasing"
-        cd $WPDIR
-        svn status
-
-        if [[ "x$DRY" = "x1" ]]
-            then
-            echo "svn ci -m \"$MESSAGE\""
-        else
-            svn ci -m "$MESSAGE"
-        fi
-
-#       if [[ "x$MAJOR" = "x1" || "x$MINOR" = "x1" ]]
-#       then
-            NEWTAG="${MAJ}.${MIN}"
-            if [[ ! "x${MICR}" = "x0" ]]
-            then
-                NEWTAG="$NEWTAG.${MICR}"
-            fi
-            LASTTAG=`ls tags | sort -n | tail -1`
-        
-            echo "checking last tag $LASTTAG versus $NEWTAG"
-            if [[ "x$LASTTAG" = "x${NEWTAG}" ]]
-            then
-                echo "Tag already exists, bailing"
-                exit
-            fi
-
-            if [[ "x$DRY" = "x1" ]]
-            then
-                echo "svn cp trunk \"tags/${NEWTAG}\""
-                echo "svn ci -m \"Tagging ${NEWTAG}\""
-            else
-                svn cp trunk "tags/${NEWTAG}"
-                svn ci -m "Tagging ${NEWTAG}"
-            fi
-#       else
-#            echo "Micro version does not get a tag"
-#       fi
-    fi
-fi
+mg create tag "${MAJ}.${MIN}.${MICR}" -m "auto tagged commit"
